name: CI model to duckhub

# Trigger
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

# Acciones
jobs:
  build_docker_image:
    runs-on: ubuntu-latest

    steps:
      - name: Check the repo
        uses: actions/checkout@v2

      - name: Login to Ducker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        run: docker build -t jvlianjg/deploy-trabajo-practico:dev .

      - name: Docker push to Ducker Hub
        run: docker push jvlianjg/deploy-trabajo-practico:dev

      - name: Login into the server
        run: echo '${{ secrets.DOCKER_PASSWORD }}' | docker login -u '${{ secrets.DOCKER_USERNAME }}' --password-stdin

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            docker login
            if docker ps --all | grep trabajo-practico; then
              docker stop trabajo-practico
              docker rm trabajo-practico
            fi 
            
            docker pull ${{ secrets.DOCKER_USERNAME }}/deploy-trabajo-practico:dev
            docker run -d --name trabajo-practico -p 8000:8000 ${{ secrets.DOCKER_USERNAME }}/deploy-trabajo-practico:dev
