name: CI model to duckhub

# Trigger
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

# Acciones
jobs:
  build_docker_image:
    runs-on: ubuntu-latest

    steps:
      - name: Check the repo
        uses: actions/checkout@v2

      - name: Login to Ducker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        run: docker build -t jvlianjg/deploy-trabajo-practico:dev .

      - name: Docker push to Ducker Hub
        run: docker push jvlianjg/deploy-trabajo-practico:dev
